# Generated by Django 5.0.2 on 2024-03-06 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lessons", "0006_categorymodel_remove_lesson_category_lessonmodel_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="LessonModel",
        ),
    ]
