# Generated by Django 5.0.2 on 2024-03-06 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lessons", "0007_delete_lessonmodel"),
    ]

    operations = [
        migrations.AddField(
            model_name="categorymodel",
            name="photo",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
    ]
