# Generated by Django 5.0.2 on 2024-03-06 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lessons", "0009_alter_categorymodel_photo"),
    ]

    operations = [
        migrations.CreateModel(
            name="LessonPage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("content", models.TextField()),
                ("slug", models.SlugField(unique=True)),
            ],
        ),
    ]
