# Generated by Django 5.0.2 on 2024-03-06 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lessons", "0010_lessonpage"),
    ]

    operations = [
        migrations.DeleteModel(
            name="LessonPage",
        ),
    ]
