# Generated by Django 5.0.2 on 2024-03-06 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lessons", "0011_delete_lessonpage"),
    ]

    operations = [
        migrations.CreateModel(
            name="Lesson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                (
                    "slug",
                    models.SlugField(
                        blank=True, max_length=100, null=True, unique=True
                    ),
                ),
                ("text", models.CharField(max_length=1000)),
            ],
        ),
        migrations.AddField(
            model_name="categorymodel",
            name="slug",
            field=models.SlugField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
