# Generated by Django 5.0.2 on 2024-03-06 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lessons", "0012_lesson_categorymodel_slug"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "lesson_name",
                    models.CharField(max_length=255, verbose_name="Название урока"),
                ),
                (
                    "slug",
                    models.SlugField(verbose_name="Это поле заполняется автоматически"),
                ),
                (
                    "min_description",
                    models.TextField(
                        max_length=100, verbose_name="Краткое описание урока"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="description_lesson/",
                        verbose_name="Изображение",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="CategoryModel",
        ),
        migrations.DeleteModel(
            name="Lesson",
        ),
    ]
