# Generated by Django 5.0.2 on 2024-03-07 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lessons", "0013_category_delete_categorymodel_delete_lesson"),
    ]

    operations = [
        migrations.CreateModel(
            name="Lesson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="Титул урока"
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        max_length=200,
                        null=True,
                        unique=True,
                        verbose_name="URL",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="lesson_image/",
                        verbose_name="Изображение урока",
                    ),
                ),
                ("lesson", models.TextField()),
            ],
        ),
    ]
