# Generated by Django 5.0.2 on 2024-03-07 07:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lessons", "0014_lesson"),
    ]

    operations = [
        migrations.AddField(
            model_name="lesson",
            name="category",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lessons",
                to="lessons.category",
            ),
        ),
    ]
