# Generated by Django 5.0.2 on 2024-03-07 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lessons", "0017_alter_category_slug"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="lesson",
            name="slug",
        ),
    ]
