# Generated by Django 5.0.2 on 2024-03-07 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lessons", "0018_remove_lesson_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="lesson",
            name="slug",
            field=models.SlugField(
                blank=True, max_length=200, null=True, unique=True, verbose_name="URL"
            ),
        ),
    ]
