# Generated by Django 5.0.2 on 2024-03-08 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lessons", "0020_alter_lesson_lesson"),
    ]

    operations = [
        migrations.AddField(
            model_name="lesson",
            name="link",
            field=models.URLField(blank=True, null=True, verbose_name="Ссылка"),
        ),
    ]
